name: Build Wheels and Publish Onion Package

on:
#   push:
#     branches: [main, dev]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} with CUDA support
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
    strategy:
        matrix:
            os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install cibuildwheel and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel twine
          pip install -r requirements.txt

      - name: Build wheel with cibuildwheel (Linux CUDA)
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: "nvidia/cuda:11.8.0-devel-ubuntu22.04"
          CIBW_ENVIRONMENT_LINUX: 'CMAKE_ARGS="-DUSE_CUDA=ON"'
          CIBW_BUILD: "cp310-manylinux_x86_64"

      - name: Publish Package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse/
          repository-url: https://test.pypi.org/legacy/

    #   - name: Publish Package to PyPI
    #     uses: pypa/gh-action-pypi-publish@release/v1
    #     with:
    #       packages-dir: build/wheels
