name: Build Wheels and Publish Onion Package

on:
#   push:
#     branches: [main, dev]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} with CUDA support
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel twine
          pip install -r requirements.txt

      - name: Build wheel with cibuildwheel (Linux CUDA)
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_ALL_LINUX: |
            set -euxo pipefail
            yum install -y yum-utils
            CUDA_REPO="https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo"
            yum-config-manager --add-repo "${CUDA_REPO}"
            yum clean all
            yum install -y cuda-toolkit-11-8 cuda-compiler-11-8 cuda-libraries-devel-11-8
            /usr/local/cuda-11.8/bin/nvcc --version
          CIBW_ENVIRONMENT_LINUX: |
            CMAKE_ARGS="-DUSE_CUDA=ON"
            PATH="$PATH:/usr/local/cuda-11.8/bin"
            CMAKE_PREFIX_PATH="/usr/local/cuda-11.8:${CMAKE_PREFIX_PATH:-}"
            LD_LIBRARY_PATH="/usr/local/cuda-11.8/lib64:${LD_LIBRARY_PATH:-}"
            CMAKE_CUDA_COMPILER=/usr/local/cuda-11.8/bin/nvcc
          CIBW_BUILD: "cp3{8,9,10,11,12}-manylinux_x86_64" 
          CIBW_ARCHS_LINUX: x86_64

      - name: Publish Package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse/
          repository-url: https://test.pypi.org/legacy/

    #   - name: Publish Package to PyPI
    #     uses: pypa/gh-action-pypi-publish@release/v1
    #     with:
    #       packages-dir: build/wheels
